services:
  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: >
      consul agent -server -ui -node=server-1 -bootstrap-expect=1
      -client=0.0.0.0 -bind=0.0.0.0 -datacenter=dc1
    networks:
      - consul-net

  servicio-usuarios:
    build: .
    command: node servicio-usuarios.js
    ports:
      - "3001:3001"
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - consul-net

  servicio-pedidos:
    build: .
    command: node servicio-pedidos.js
    ports:
      - "3002:3002"
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      - consul
      - servicio-usuarios
    networks:
      - consul-net

networks:
  consul-net:
    driver: bridge